### ISSUE TITLE
Problem with json AWS SNS message

### ISSUE THREAD

**Issue by wdarking** [octohk/feedback#1]
There is a problem rendering the webhook details when the payload message is a json from AWS SNS. Maybe it's something related to the json escaping inside the payload?

Here is a gif showing a simple message and a json message published with SNS:

![o1mIzl3mPk](https://user-images.githubusercontent.com/14166369/84146600-50dd7980-aa32-11ea-9892-fce4f6791a2e.gif)

As you can see, there is a console error:

```
Uncaught (in promise) SyntaxError: Unexpected token F in JSON at position 40
    at JSON.parse (<anonymous>)
```

**Comment by slashequip** [comment]
Thanks for reporting this @wdarking, we spotted this one too. As you pointed out, it seems to be due to escaping, when having a json string inside a json object. 

We will be working on a fix for this today! 

Thanks again 💜

**Comment by slashequip** [comment]
👋 @wdarking, we've just pushed a fix for this now. You webhooks should be visible and readable now! Feel free to reopen this issue if there is anything else related.

Thanks again for the great issue report and congrats on being issue #1! Let us know if there is anything else we can do for you. 🐙
