### ISSUE TITLE
Hi! are there any static outgoing IPs?

### ISSUE THREAD

**Issue by nazonoz** [octohk/feedback#13]
I need whitelist this webhook on my server.. or won't work.
Are there any static IPs?

Thanks.

**Comment by slashequip** [comment]
Hey @nazonoz,

Sorry for the delay here, I missed this issue being opened 😿

You can currently use; 161.35.127.138

This may change in the future but we will alert our customers should we make a change here.

**Comment by nazonoz** [comment]
@slashequip
Oh, thank you very much!
this helps me a lot!
as a non-developer, your site is like a god!😍😍

**Comment by slashequip** [comment]
Thank you for the kind word @nazonoz, feel free to send any feedback, good and bad, as you use Octohook, love to hear how people are using us and how we can improve!
