### ISSUE TITLE
Custom function to format the original payload and redirect to another endpoint

### ISSUE THREAD

**Issue by noook** [octohk/feedback#2]
This would look like serverless function, you choose your language and a function accepts some arguments: Payload, Context

You format your payload into what suits you the best

Then redirect the formatted payload somewhere else where it will trigger another action (ex: IFTTT with their custom values `value1`, `value2` and `value3` to form a sentence

Or custom JSON with JSON path syntax to fill values

**Comment by slashequip** [comment]
Hey @noook 👋, thanks for the feedback! Forwarding and 'destinations' are something that are absolutely on our roadmap (the one we haven't published anywhere yet! 😅) and we plan to introduce them prior to coming out of beta.

When it comes to the transformation side of thing we really want to get this right, we want to make this feature intuitive, simple (as possible) and not _necessarily_ just a code editor for developers to smash anything in to.

The implementation is certainly still up in the air so we will be listening to any other feedback that comes in, I'll be sure to keep you in the loop! Thanks again 🐙

**Comment by slashequip** [comment]
Hey @noook, I know this doesn't take care of the exact issue described here but we release 'destinations' this week, for now just a simple forward-to-url as is, but, as discussed, we plan to take this further relatively soonish on the roadmap. Just figured I'd let you know in case you missed it on Twitter :)

**Comment by lorisleiva** [comment]
Hi @noook 👋 

This week we've released **webhook workflows** (for free for everyone).

That means you can now configure just about everything from receiving the webhook to forwarding it somewhere else.

Here's a blog post introducing the feature including a little demo:

https://lorisleiva.com/introducing-webhook-workflows/

I hope you enjoy it. Let us know what you think! 🥰 

<img width="1200" alt="Frame 6" src="https://user-images.githubusercontent.com/3642397/108201465-c4826b00-7117-11eb-8c36-d9052d960945.png">

**Comment by slashequip** [comment]
> we plan to take this further relatively soonish on the roadmap

The classic 'soon'; 8 months later.....

But I think this should more than fulfil your needs @noook! ❤️
