### ISSUE TITLE
Allow custom source

### ISSUE THREAD

**Issue by noook** [octohk/feedback#3]
In #2 it was told that forwarding was possible. In addition of this feature, allowing any source to send events would make Octohook a great tool to debug Messenger chatbot requests for languages that don't allow debugging when you're not the initiator of the requests.

Ex: In Symfony, you can't log a request made by someone that is not you unless you store the payload in a file. calling `dump()` will return the dump to Messenger, and sometimes you just need to read the content to debug / inspect payload / prepare your code.

**Comment by slashequip** [comment]
Hey @noook 👋,

Not exactly sure what you mean with this one, we do allow custom sources that don't do any parsing of the data for the timeline section. Is this not what you mean here?

Thanks!

**Comment by noook** [comment]
Sorry, must have been a long day if I can't read "Custom" properly...
