### ISSUE TITLE
[Feature request] Payload signing

### ISSUE THREAD

**Issue by kieranajp** [octohk/feedback#4]
Hey chaps <3

It would be cool to verify webhook signatures in Octohook, so you have a centralised place to do so.

This would look something like:

- when adding a webhook, ask for an optional secret
- `HMAC('sha256', payload, secret)`
- If invalid, reject the webhook with 401

This'd be useful for, e.g., [Stripe](https://stripe.com/docs/webhooks/signatures#verify-manually)

**Comment by lorisleiva** [comment]
Hi @kieranajp 👋 

This week we've released **webhook workflows** (for free for everyone).

That means you can now configure just about everything from receiving the webhook to forwarding it somewhere else. This includes providing your own custom logic around webhook validation.

Here's a blog post introducing the feature including a little demo:

https://lorisleiva.com/introducing-webhook-workflows/

In the demo I implement a workflow that verifies the signature of Sentry webhooks by creating a HMAC and comparing it with the signature in the headers.

I hope you enjoy it. Let us know what you think! 🥰 

<img width="1200" alt="Frame 6" src="https://user-images.githubusercontent.com/3642397/108201465-c4826b00-7117-11eb-8c36-d9052d960945.png">
