### ISSUE TITLE
[Feature request] Export requests

### ISSUE THREAD

**Issue by kieranajp** [octohk/feedback#5]
Use case: After receiving a request in Octohook, I want to be able to easily make modifications to that request and forward it to the API I'm developing.

The simplest expression of this would be providing the raw JSON of a request for me to copy and paste, alongside the foldable `var_export` style view. Better yet would be providing a curl of the incoming request which can then be imported into Postman / Insomnia etc.

**Comment by lorisleiva** [comment]
Hey @kieranajp 👋 

Thanks for the feedback. This is now live. 🍺 

<img width="1427" alt="CleanShot 2021-01-11 at 16 50 18@2x" src="https://user-images.githubusercontent.com/3642397/104213432-2c190c80-542e-11eb-8a3b-72b7c704d528.png">

**Comment by kieranajp** [comment]
Perfect timing too <3
