### ISSUE TITLE
[Feature request] Labelling webhooks

### ISSUE THREAD

**Issue by kieranajp** [octohk/feedback#6]
At the moment, my sidebar is full of user agents, which isn't particularly useful:

![image](https://user-images.githubusercontent.com/681426/104213837-05130880-5437-11eb-9ec1-34186c4c5531.png)

It would be awesome if I could either rename these, or add labels to them. For example, I know that in the above screenshot the second request down is a webhook payload for a bounced email - I would love to be able to see that at a glance from the sidebar.

**Comment by kieranajp** [comment]
Wow, that image came out massive, apologies.

**Comment by lorisleiva** [comment]
You make a good point. We've got in the pipeline the ability to configure what to use as a title and subtitle for these cards — using the upcoming node manager — but we didn't think about manually labelling them. Thanks for the feedback!

**Comment by lorisleiva** [comment]
Hey Kieran, just to let you know that you can now update and search the title and subtitle of each webhook.

Enjoy! ☺️ 

![Frame 8](https://user-images.githubusercontent.com/3642397/105221830-8febb580-5b51-11eb-9ebe-d5fe7518be86.jpg)
