### ISSUE TITLE
[Feature request] Add base64 encode to hash text

### ISSUE THREAD

**Issue by CaporalDead** [octohk/feedback#8]
Hi !

FIrst, thanks for your great work :).

It would be very nice if you could add "base64 encode" to hash texts functions. Some web services encode the signed payload into a header with as a base 64 encoded string.

Tell me if you need more infos about the usecase or if my request is unclear.

Have a great day !

**Comment by slashequip** [comment]
Hey @CaporalDead, thanks for the kind words! 😄 

That makes sense to us! We can certainly add base64 encoding and decoding, we just need to have a think about where we add this, as we will probably need a new section for encoding/decoding as they are a little different to hashing.

Will get to this as soon as possible and I'll keep you updated.

Thank- have a great day too!

**Comment by CaporalDead** [comment]
Thanks for your quick feedback :)

**Comment by lorisleiva** [comment]
Hi again 👋 

We've added the `Base64 encode` and `Base64 decode` operations to the `Transform text` node.

Thank you for helping us making Octohook better. 😊 

<img width="826" alt="Capture 2021-03-02T17 23 17@2x" src="https://user-images.githubusercontent.com/3642397/109688457-2f9e5980-7b7c-11eb-9cb0-3ddd70c5274e.png">
